### ISSUE TITLE
Can this be used on a Plesk Server?

### ISSUE THREAD

**Issue by gelsas** [tine20/syncroton#18]
Hello,

I just found your ActiveSync implementation and wanted to ask if this could be used on an Plesk server to enable all email addresses which are existing on the Plesk server to sync contacts, calendars etc. (https://www.plesk.com/)

If it is possible how exactly do I need to set it up myself?

**Comment by msphn** [comment]
So syncroton is a library which can be used to implement activesync abilities but it's not a standalone application.
You can check out https://github.com/tine20/tine20 which implements syncroton and provides a fully featured implemetation.

And about plesk there is no yes or no answer, it depends on what PHP packages are actually installed and what the server itself is capable of. Most likely the answer is yes.

Does it answer your question?

**Comment by gelsas** [comment]
Yes I think it answers the question.

I was hoping to be able to use this to easily enhance the experience for my users. 

Sadly I am not a developer myself otherwise I would have created a free Plesk extension to enable such functionality for every plesk user.

Thank you for the quick response.

**Comment by msphn** [comment]
You are welcome!

@pschuele can't close this one :-)
